BEGIN TRANSACTION;


INSERT INTO artist (name, url) VALUES ('SPARTALIEN', 'https://spartalien.com');
INSERT INTO artist (name, url) VALUES ('Esblendet', 'https://esblendet.ch');
INSERT INTO artist (name, url) VALUES ('SPARTALIEN & Esblendet', NULL);
INSERT INTO artist (name, url) VALUES ('Stevie Lee Price', 'https://twitter.com/STEVIELEEPRICE');
INSERT INTO artist (name, url) VALUES ('SPARTALIEN & Stevie Lee Price', NULL);
INSERT INTO artist (name, url) VALUES ('ediblewaves', 'https://twitter.com/STEVIELEEPRICE');
INSERT INTO artist (name, url) VALUES ('ediblewaves & SPARTALIEN', NULL);
INSERT INTO artist (name, url) VALUES ('Orochi Hanma', 'https://twitch.tv/orochihanma');


INSERT INTO label (name, url) VALUES ('Kaiseki Digital', 'https://kaisekidigital.bandcamp.com');
INSERT INTO label (name, url) VALUES ('<1', 'https://lessthanone.bandcamp.com');
INSERT INTO label (name, url) VALUES ('Sounds for the Soul Records', 'https://soundsforthesoul.bandcamp.com');


INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Continuoduction', 396);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'I''ll Embrace You Again In Space', 418);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Realize It''s Just A Ride', 360);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Nature''s Song', 362);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Following The Calling', 421);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Digging In Memories', 518);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Heat-Resistant', 427);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Song For Wind', 522);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Messaggio Per Naelog', 151);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Martina', 286);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Time', 318);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Every Day', 360);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Setting The Mood (Intro)', 234);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Calling You', 251);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Transformation', 579);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Denial (Interlude 1)', 93);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Clinging', 486);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Deadline', 385);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Blurry Sight (Interlude 2)', 117);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Moping', 326);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Drifting', 348);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Approach (Interlude 3)', 163);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Unforeseen End', 395);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Il Tramonto Del Sole', 319);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Good Bye Cruel World (Outro)', 304);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Searching', 306);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Craving For Change', 445);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Devil''s Lure', 279);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Last Card', 300);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Campfires', 322);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Start of Transmission (Intro)', 98);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Incantare', 573);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Spelunca', 546);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'S2x4 (Interlude 1)', 98);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Suspirare', 455);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Paenitentia', 520);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'R6Y7x2 (Interlude 2)', 98);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Crudelitas', 513);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Immori', 322);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'I1I1M7x2 (Interlude 3)', 98);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Requirere', 316);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Desiderium', 465);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'End of Transmission (Outro)', 98);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Frozen Memories', 402);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #1', 2220);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #2', 2346);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #3', 1172);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'They Shot My Friend', 375);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Sad Lightness Of Being', 568);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #4', 3584);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #5', 2153);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #6', 1307);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #7', 332);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Roadblock', 160);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Escape', 229);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Freedom', 265);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Vigilant', 163);
INSERT INTO track (artist_id, name, runtime) VALUES (3, 'Rainbows & Unicorns', 265);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #8', 962);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 1', 3586);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 1 (Waveless Mix)', 3586);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #9', 1727);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Unfamiliar (Intro)', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Nightlife', 516);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Together', 659);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Transitting Wormhole S9A5-1 (Interlude 1)', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Ghosts', 470);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Help', 681);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Transitting Wormhole S9A5-2 (Interlude 2)', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Utopia', 909);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Crossroads', 587);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Transitting Wormhole S9A5-3 (Interlude 3)', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Ragazzi', 445);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Realm', 328);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Singularity (Outro)', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Brain I/O #10', 612);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 2', 3584);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 2 (Binaural Headphone Mix)', 3584);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 2 (Weatherless Mix)', 3584);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Let It All Go, Volume 2 (Weatherless & Droneless Mix)', 3584);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Wooden Bench', 278);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Reconquer', 225);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Answering Machine', 306);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Sandy Ice Cream', 284);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Detuned Present', 409);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'After All', 330);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Push', 312);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Rusty Playground', 388);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Pull', 232);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'You Are Not Them', 335);
INSERT INTO track (artist_id, name, runtime) VALUES (1, '[Bonus Track] A Night With My Imaginary Friend', 351);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Uncertain', 268);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Anomaly', 204);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Secret', 247);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Polychrome', 236);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Irresistible', 237);
INSERT INTO track (artist_id, name, runtime) VALUES (4, 'Flux (feat. Stevie Lee Price)', 289);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Flux (Instrumental Mix)', 289);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Flux (Ambient Mix)', 289);
INSERT INTO track (artist_id, name, runtime) VALUES (7, 'Haphe (SPARTALIEN''s Wicca Remix)', 523);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Once', 116);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Maybe', 188);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Mountain', 142);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Ice', 122);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Why', 134);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Real', 97);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Same', 157);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Tower', 118);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Not', 92);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: If', 122);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Tales', 49);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Unconditional', 84);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Arrival', 57);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: With', 77);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Stumble', 60);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Torpedo', 138);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Sometime', 105);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 1: Castle', 61);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Prayer', 193);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Wait', 156);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Cargo', 123);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Volcano', 82);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Cave', 87);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Resolution', 107);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Reunion', 100);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Decay', 175);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Breach', 139);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Unlocked', 72);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 2: Thrive', 120);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Three', 176);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Valley', 164);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Rope', 100);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Carusel', 79);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Angel', 65);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Miss', 120);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Here', 118);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Envelope', 73);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Chapter 3: Alps', 128);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Doomer''s Delight: Chapter 1', 3324);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Doomer''s Delight: Chapter 2', 2452);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Doomer''s Delight: Chapter 3', 1812);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Four Four Three', 122);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'City Lights', 134);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Final Adventure', 121);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'El Loco', 124);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Tracked', 99);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Smoking Sea', 224);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Four Four Three (We Ded Version)', 122);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Final Adventure (Not A Tale Version)', 121);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Smoking Sea (feat. Orochi Hanma)', 227);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Compost Heap Triangle', 164);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'To Return Home', 278);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Memory', 298);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Biting Wind', 330);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'With Darkness Comes Clarity', 194);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Full Moon', 365);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'His Task', 346);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Knees On The Floor', 206);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Never Arriving', 148);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Collective Departure', 183);
INSERT INTO track (artist_id, name, runtime) VALUES (1, '[Bonus Track] I Have Seen The Shadow Again', 366);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 1', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 2', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 3', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 4', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 5', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 6', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 7', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 8', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 9', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'The Dying Spaceship Symphony: Part 10', 3600);
INSERT INTO track (artist_id, name, runtime) VALUES (1, 'Yellow Soul Grinder', 600);


INSERT INTO track_credit (track_id, line) VALUES (4, 'Speech - Alan Watts (alanwatts.org)');
INSERT INTO track_credit (track_id, line) VALUES (58, 'Pan Drum - Esblendet');
INSERT INTO track_credit (track_id, line) VALUES (58, 'Guzheng - Esblendet');


INSERT INTO rls_type (name) VALUES ('Single');
INSERT INTO rls_type (name) VALUES ('EP');
INSERT INTO rls_type (name) VALUES ('Album');
INSERT INTO rls_type (name) VALUES ('Remix');


INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Continuoduction', '2016-03-24');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'I''ll Embrace You Again In Space', '2016-10-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Realize It''s Just A Ride', '2017-03-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Nature''s Song', '2017-06-18');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Following The Calling', '2017-06-20');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Digging In Memories', '2017-07-03');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Heat-Resistant', '2017-07-15');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Song For Wind', '2017-08-10');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Messaggio Per Naelog', '2017-08-25');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Martina', '2017-09-22');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Time', '2017-10-22');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Every Day', '2018-02-27');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'MONOLOG', '2018-05-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Searching', '2018-08-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 2, 'THE GREAT FILTER', '2018-08-31');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, '2358', '2019-03-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Frozen Memories', '2019-03-29');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date, upd_date) VALUES (1, 3, 'BRAIN I/O', '2019-06-09', '2020-07-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'They Shot My Friend', '2019-07-07');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'The Sad Lightness Of Being', '2019-07-07');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 2, 'KEEN', '2019-12-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (3, 1, 'SPARTALIEN & Esblendet - Rainbows & Unicorns', '2019-12-23');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'LET IT ALL GO, Volume 1', '2020-02-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, '1996', '2020-06-26');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'LET IT ALL GO, Volume 2', '2020-09-03');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'CHILL TRACKS 2016-2020', '2020-12-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'FLOATING HIGH', '2021-01-01');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Uncertain', '2021-05-07');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 2, 'THE BAND WITH THE DRUMMER WHO KNEW ONLY ONE RHYTHM', '2021-06-07');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (5, 1, 'Flux', '2021-08-13');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (7, 4, 'ediblewaves - Haphe (SPARTALIEN''s Wicca Remix)', '2021-08-31');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'UNTOLD STORIES', '2021-09-22');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'UNTOLD STORIES (Doomer''s Delight)', '2021-09-22');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'OKAY, BUT CAN YOU RAP TO THIS?', '2022-11-23');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'WARM SUMMER EVENING', '2023-04-21');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 3, 'THE DYING SPACESHIP SYMPHONY', '2023-06-17');
INSERT INTO rls (artist_id, rls_type_id, name, pub_date) VALUES (1, 1, 'Yellow Soul Grinder', '2023-07-13');


INSERT INTO rls_credit (rls_id, line) VALUES (1, 'Coverart photo - NASA (nasa.gov)');
INSERT INTO rls_credit (rls_id, line) VALUES (4, 'Cover art photo - Unknown Photographer (it''s a Bush TV22)');
INSERT INTO rls_credit (rls_id, line) VALUES (22, 'Coverart Unicorn - Unknown Artist');
INSERT INTO rls_credit (rls_id, line) VALUES (22, 'Coverart Rainbow Texture - kitti851');
INSERT INTO rls_credit (rls_id, line) VALUES (32, 'Recorded, composed, mixed and mastered by SPARTALIEN (spartalien.com) between July and August 2021.');


INSERT INTO rls_tracklist (rls_id, track_id) VALUES (1, 1);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (2, 2);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (3, 3);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (4, 4);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (5, 5);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (6, 6);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (7, 7);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (8, 8);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (9, 9);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (10, 10);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (11, 11);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (12, 12);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 13);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 14);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 15);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 16);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 17);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 18);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 19);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 20);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 21);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 22);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 23);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 24);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (13, 25);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (14, 26);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (15, 27);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (15, 28);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (15, 29);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (15, 30);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 31);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 32);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 33);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 34);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 35);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 36);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 37);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 38);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 39);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 40);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 41);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 42);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (16, 43);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (17, 44);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 45);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 46);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 47);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 50);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 51);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 52);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 53);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 59);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 62);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (18, 76);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (19, 48);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (20, 49);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (21, 54);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (21, 55);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (21, 56);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (21, 57);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (22, 58);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (23, 60);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (23, 61);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 63);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 64);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 65);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 66);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 67);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 68);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 69);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 70);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 71);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 72);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 73);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 74);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (24, 75);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (25, 77);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (25, 78);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (25, 79);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (25, 80);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 1);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 9);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 10);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 11);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 15);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 24);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 33);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 44);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 58);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 32);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (26, 77);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 81);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 82);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 83);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 84);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 85);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 86);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 87);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 88);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 89);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 90);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (27, 91);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (28, 92);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (29, 93);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (29, 94);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (29, 95);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (29, 96);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (30, 97);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (30, 98);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (30, 99);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (31, 100);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 101);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 102);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 103);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 104);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 105);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 106);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 107);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 108);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 109);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 110);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 111);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 112);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 113);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 114);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 115);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 116);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 117);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 118);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 119);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 120);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 121);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 122);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 123);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 124);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 125);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 126);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 127);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 128);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 129);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 130);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 131);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 132);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 133);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 134);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 135);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 136);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 137);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (32, 138);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (33, 139);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (33, 140);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (33, 141);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 142);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 143);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 144);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 145);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 146);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 147);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 148);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 149);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (34, 150);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 151);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 152);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 153);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 154);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 155);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 156);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 157);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 158);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 159);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 160);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (35, 161);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 162);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 163);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 164);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 165);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 166);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 167);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 168);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 169);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 170);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (36, 171);
INSERT INTO rls_tracklist (rls_id, track_id) VALUES (37, 172);


INSERT INTO rls_media (rls_id, code) VALUES (1, '{"type": "youtubeVideo", "slug":"QZovE8JDsXU"}');
INSERT INTO rls_media (rls_id, code) VALUES (9, '{"type":"youtubeVideo", "slug":"QfDUgPrOhbA"}');
INSERT INTO rls_media (rls_id, code) VALUES (35, '{"type":"youtubePlaylist", "slug":"PLGOlCfPCyZ4EHWNjgL5g5bRG6bur9dUXf"}');


INSERT INTO dist_track (track_id, platform, url) VALUES (1, 'bandcamp', 'https://spartalien.bandcamp.com/track/continuoduction');
INSERT INTO dist_track (track_id, platform, url) VALUES (1, 'spotify', 'https://open.spotify.com/track/2Clx7jPmYSA21DbB0FKxUR');
INSERT INTO dist_track (track_id, platform, url) VALUES (2, 'bandcamp', 'https://spartalien.bandcamp.com/track/ill-embrace-you-again-in-space');
INSERT INTO dist_track (track_id, platform, url) VALUES (2, 'spotify', 'https://open.spotify.com/track/3QmCKvjLtKXS4vQD6822rf');
INSERT INTO dist_track (track_id, platform, url) VALUES (3, 'bandcamp', 'https://spartalien.bandcamp.com/track/realize-its-just-a-ride');
INSERT INTO dist_track (track_id, platform, url) VALUES (3, 'spotify', 'https://open.spotify.com/track/7LwAhr4FxPmxhsM0X4C2h6');
INSERT INTO dist_track (track_id, platform, url) VALUES (4, 'bandcamp', 'https://spartalien.bandcamp.com/track/natures-song');
INSERT INTO dist_track (track_id, platform, url) VALUES (4, 'spotify', 'https://open.spotify.com/track/0Fnu4vn6XsiUpI2ECJyr5K');
INSERT INTO dist_track (track_id, platform, url) VALUES (5, 'bandcamp', 'https://spartalien.bandcamp.com/track/following-the-calling');
INSERT INTO dist_track (track_id, platform, url) VALUES (5, 'spotify', 'https://open.spotify.com/track/5DlhcOQXlUESTOhNWL4wQ5');
INSERT INTO dist_track (track_id, platform, url) VALUES (6, 'bandcamp', 'https://spartalien.bandcamp.com/track/digging-in-memories');
INSERT INTO dist_track (track_id, platform, url) VALUES (6, 'spotify', 'https://open.spotify.com/track/5JmknWTUqtJZ2Qhb3MMoCo');
INSERT INTO dist_track (track_id, platform, url) VALUES (7, 'bandcamp', 'https://spartalien.bandcamp.com/track/heat-resistant');
INSERT INTO dist_track (track_id, platform, url) VALUES (7, 'spotify', 'https://open.spotify.com/track/3VikP8t1yyx98cPKTinZDO');
INSERT INTO dist_track (track_id, platform, url) VALUES (8, 'bandcamp', 'https://spartalien.bandcamp.com/track/song-for-wind');
INSERT INTO dist_track (track_id, platform, url) VALUES (8, 'spotify', 'https://open.spotify.com/track/6Y5r9u7mHDudhTx90XTEF3');
INSERT INTO dist_track (track_id, platform, url) VALUES (9, 'bandcamp', 'https://spartalien.bandcamp.com/track/messaggio-per-naelog');
INSERT INTO dist_track (track_id, platform, url) VALUES (9, 'spotify', 'https://open.spotify.com/track/2bwflOuvNhQgtaCA4zI40e');
INSERT INTO dist_track (track_id, platform, url) VALUES (10, 'bandcamp', 'https://spartalien.bandcamp.com/track/martina');
INSERT INTO dist_track (track_id, platform, url) VALUES (10, 'spotify', 'https://open.spotify.com/track/6FSbzkJMMxfi9o2QopDW2W');
INSERT INTO dist_track (track_id, platform, url) VALUES (11, 'bandcamp', 'https://spartalien.bandcamp.com/track/time');
INSERT INTO dist_track (track_id, platform, url) VALUES (11, 'spotify', 'https://open.spotify.com/track/3AGRNrD23jzBOThTUGvygn');
INSERT INTO dist_track (track_id, platform, url) VALUES (12, 'bandcamp', 'https://spartalien.bandcamp.com/track/every-day');
INSERT INTO dist_track (track_id, platform, url) VALUES (12, 'spotify', 'https://open.spotify.com/track/3XStzziKE8h0Hzw6cT5OAd');
INSERT INTO dist_track (track_id, platform, url) VALUES (13, 'bandcamp', 'https://spartalien.bandcamp.com/track/setting-the-mood-intro');
INSERT INTO dist_track (track_id, platform, url) VALUES (13, 'spotify', 'https://open.spotify.com/track/5ur6odmpd8TQzb9mu54L13');
INSERT INTO dist_track (track_id, platform, url) VALUES (14, 'bandcamp', 'https://spartalien.bandcamp.com/track/calling-you');
INSERT INTO dist_track (track_id, platform, url) VALUES (14, 'spotify', 'https://open.spotify.com/track/29rXn1MGNwPEYNI0a9xPjN');
INSERT INTO dist_track (track_id, platform, url) VALUES (15, 'bandcamp', 'https://spartalien.bandcamp.com/track/transformation');
INSERT INTO dist_track (track_id, platform, url) VALUES (15, 'spotify', 'https://open.spotify.com/track/79r2WMH7HP2ObHmmiCC4FP');
INSERT INTO dist_track (track_id, platform, url) VALUES (16, 'bandcamp', 'https://spartalien.bandcamp.com/track/denial-interlude-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (16, 'spotify', 'https://open.spotify.com/track/74i5KgBZVbdLqUpChlmCJO');
INSERT INTO dist_track (track_id, platform, url) VALUES (17, 'bandcamp', 'https://spartalien.bandcamp.com/track/clinging');
INSERT INTO dist_track (track_id, platform, url) VALUES (17, 'spotify', 'https://open.spotify.com/track/2BJ5TaUH2bBpSShnzIsQHQ');
INSERT INTO dist_track (track_id, platform, url) VALUES (18, 'bandcamp', 'https://spartalien.bandcamp.com/track/deadline');
INSERT INTO dist_track (track_id, platform, url) VALUES (18, 'spotify', 'https://open.spotify.com/track/6V0PZxWorYnSpfd3dmgEhc');
INSERT INTO dist_track (track_id, platform, url) VALUES (19, 'bandcamp', 'https://spartalien.bandcamp.com/track/blurry-sight-interlude-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (19, 'spotify', 'https://open.spotify.com/track/1ITvOk5TsMIjAAvMHF4H4I');
INSERT INTO dist_track (track_id, platform, url) VALUES (20, 'bandcamp', 'https://spartalien.bandcamp.com/track/moping');
INSERT INTO dist_track (track_id, platform, url) VALUES (20, 'spotify', 'https://open.spotify.com/track/6weqsiXr8mtjjMaKfdMqgX');
INSERT INTO dist_track (track_id, platform, url) VALUES (21, 'bandcamp', 'https://spartalien.bandcamp.com/track/drifting');
INSERT INTO dist_track (track_id, platform, url) VALUES (21, 'spotify', 'https://open.spotify.com/track/3t0EygHwCbzrrSUQGpymWL');
INSERT INTO dist_track (track_id, platform, url) VALUES (22, 'bandcamp', 'https://spartalien.bandcamp.com/track/approach-interlude-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (22, 'spotify', 'https://open.spotify.com/track/0LIgV49H88ZkK6UKZgk07D');
INSERT INTO dist_track (track_id, platform, url) VALUES (23, 'bandcamp', 'https://spartalien.bandcamp.com/track/unforeseen-end');
INSERT INTO dist_track (track_id, platform, url) VALUES (23, 'spotify', 'https://open.spotify.com/track/4LzVjFp0EOklES1CSVHknm');
INSERT INTO dist_track (track_id, platform, url) VALUES (24, 'bandcamp', 'https://spartalien.bandcamp.com/track/il-tramonto-del-sole');
INSERT INTO dist_track (track_id, platform, url) VALUES (24, 'spotify', 'https://open.spotify.com/track/2cdXGmXi8fN85POLGBdRZd');
INSERT INTO dist_track (track_id, platform, url) VALUES (25, 'bandcamp', 'https://spartalien.bandcamp.com/track/good-bye-cruel-world-outro');
INSERT INTO dist_track (track_id, platform, url) VALUES (25, 'spotify', 'https://open.spotify.com/track/3EqMYFQe5Vjpu5J4gkcckX');
INSERT INTO dist_track (track_id, platform, url) VALUES (26, 'bandcamp', 'https://spartalien.bandcamp.com/track/searching');
INSERT INTO dist_track (track_id, platform, url) VALUES (26, 'spotify', 'https://open.spotify.com/track/0zFZIbuKaLJ0bm9MecHfk0');
INSERT INTO dist_track (track_id, platform, url) VALUES (27, 'bandcamp', 'https://spartalien.bandcamp.com/track/craving-for-change');
INSERT INTO dist_track (track_id, platform, url) VALUES (27, 'spotify', 'https://open.spotify.com/track/0ES940tpYrfrJo9VFpFLJT');
INSERT INTO dist_track (track_id, platform, url) VALUES (28, 'bandcamp', 'https://spartalien.bandcamp.com/track/devils-lure');
INSERT INTO dist_track (track_id, platform, url) VALUES (28, 'spotify', 'https://open.spotify.com/track/1t3VBiPIBIjtAetrN55AVa');
INSERT INTO dist_track (track_id, platform, url) VALUES (29, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-last-card');
INSERT INTO dist_track (track_id, platform, url) VALUES (29, 'spotify', 'https://open.spotify.com/track/1H6GPU7yVjx2GUhsMnM0DL');
INSERT INTO dist_track (track_id, platform, url) VALUES (30, 'bandcamp', 'https://spartalien.bandcamp.com/track/campfires');
INSERT INTO dist_track (track_id, platform, url) VALUES (30, 'spotify', 'https://open.spotify.com/track/5byHjniOidfVH1fXricnxe');
INSERT INTO dist_track (track_id, platform, url) VALUES (31, 'bandcamp', 'https://spartalien.bandcamp.com/track/start-of-transmission-intro');
INSERT INTO dist_track (track_id, platform, url) VALUES (31, 'spotify', 'https://open.spotify.com/track/0xpfF0AgmQfzoYwnnRLV3f');
INSERT INTO dist_track (track_id, platform, url) VALUES (32, 'bandcamp', 'https://spartalien.bandcamp.com/track/incantare');
INSERT INTO dist_track (track_id, platform, url) VALUES (32, 'spotify', 'https://open.spotify.com/track/4qxWuUuqNMkkw8kB4kDGfP');
INSERT INTO dist_track (track_id, platform, url) VALUES (33, 'bandcamp', 'https://spartalien.bandcamp.com/track/spelunca');
INSERT INTO dist_track (track_id, platform, url) VALUES (33, 'spotify', 'https://open.spotify.com/track/2Vq3uKLlcyaJ5DxjKUg9z7');
INSERT INTO dist_track (track_id, platform, url) VALUES (34, 'bandcamp', 'https://spartalien.bandcamp.com/track/s2x4-interlude-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (34, 'spotify', 'https://open.spotify.com/track/3wAPPmYvjVvDHO0mlZExLX');
INSERT INTO dist_track (track_id, platform, url) VALUES (35, 'bandcamp', 'https://spartalien.bandcamp.com/track/suspirare');
INSERT INTO dist_track (track_id, platform, url) VALUES (35, 'spotify', 'https://open.spotify.com/track/5Me2Jo1xpFEmLx5gA5Kwml');
INSERT INTO dist_track (track_id, platform, url) VALUES (36, 'bandcamp', 'https://spartalien.bandcamp.com/track/paenitentia');
INSERT INTO dist_track (track_id, platform, url) VALUES (36, 'spotify', 'https://open.spotify.com/track/2H0z46LWga8LW4d6HJ7HxH');
INSERT INTO dist_track (track_id, platform, url) VALUES (37, 'bandcamp', 'https://spartalien.bandcamp.com/track/r6y7x2-interlude-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (37, 'spotify', 'https://open.spotify.com/track/4HYM7jrVXjWIY5ux8wRfGL');
INSERT INTO dist_track (track_id, platform, url) VALUES (38, 'bandcamp', 'https://spartalien.bandcamp.com/track/crudelitas');
INSERT INTO dist_track (track_id, platform, url) VALUES (38, 'spotify', 'https://open.spotify.com/track/5e56f27qt5cqWOHfj03LuO');
INSERT INTO dist_track (track_id, platform, url) VALUES (39, 'bandcamp', 'https://spartalien.bandcamp.com/track/immori');
INSERT INTO dist_track (track_id, platform, url) VALUES (39, 'spotify', 'https://open.spotify.com/track/71JZci7sonAsLM3U9tSO9X');
INSERT INTO dist_track (track_id, platform, url) VALUES (40, 'bandcamp', 'https://spartalien.bandcamp.com/track/i1i1m7x2-interlude-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (40, 'spotify', 'https://open.spotify.com/track/56EdU5b7n3IFcNlTeUBTjM');
INSERT INTO dist_track (track_id, platform, url) VALUES (41, 'bandcamp', 'https://spartalien.bandcamp.com/track/requirere');
INSERT INTO dist_track (track_id, platform, url) VALUES (41, 'spotify', 'https://open.spotify.com/track/5AcPBy6Hx8507G23HKSmcn');
INSERT INTO dist_track (track_id, platform, url) VALUES (42, 'bandcamp', 'https://spartalien.bandcamp.com/track/desiderium');
INSERT INTO dist_track (track_id, platform, url) VALUES (42, 'spotify', 'https://open.spotify.com/track/6jbJXFZG2IPUno1zc9Dhgf');
INSERT INTO dist_track (track_id, platform, url) VALUES (43, 'bandcamp', 'https://spartalien.bandcamp.com/track/end-of-transmission-outro');
INSERT INTO dist_track (track_id, platform, url) VALUES (43, 'spotify', 'https://open.spotify.com/track/5jRXMOBKF07MOMuKKDpMBM');
INSERT INTO dist_track (track_id, platform, url) VALUES (44, 'bandcamp', 'https://spartalien.bandcamp.com/track/frozen-memories');
INSERT INTO dist_track (track_id, platform, url) VALUES (44, 'spotify', 'https://open.spotify.com/track/6rSSRx7JdtdWdbNn7gS5Pl');
INSERT INTO dist_track (track_id, platform, url) VALUES (45, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (45, 'spotify', 'https://open.spotify.com/track/0NG4XuRNMTQ7UkLesDsaUV');
INSERT INTO dist_track (track_id, platform, url) VALUES (46, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (46, 'spotify', 'https://open.spotify.com/track/4E6WBSHEEUXDuJhUnqQkS3');
INSERT INTO dist_track (track_id, platform, url) VALUES (47, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (47, 'spotify', 'https://open.spotify.com/track/0H5lZhAHbe70OQbsx9CyBx');
INSERT INTO dist_track (track_id, platform, url) VALUES (48, 'bandcamp', 'https://spartalien.bandcamp.com/track/they-shot-my-friend');
INSERT INTO dist_track (track_id, platform, url) VALUES (48, 'spotify', 'https://open.spotify.com/track/6gcULl01jPOsWwn2EwVWHM');
INSERT INTO dist_track (track_id, platform, url) VALUES (49, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-sad-lightness-of-being');
INSERT INTO dist_track (track_id, platform, url) VALUES (49, 'spotify', 'https://open.spotify.com/track/2onyU5yxSx9FhxtBgGoykG');
INSERT INTO dist_track (track_id, platform, url) VALUES (50, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-4');
INSERT INTO dist_track (track_id, platform, url) VALUES (50, 'spotify', 'https://open.spotify.com/track/3TDZhTSYUa16ipnQoAN7Kg');
INSERT INTO dist_track (track_id, platform, url) VALUES (51, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-5');
INSERT INTO dist_track (track_id, platform, url) VALUES (51, 'spotify', 'https://open.spotify.com/track/5UixO8u1YwEc38l4zOsb9x');
INSERT INTO dist_track (track_id, platform, url) VALUES (52, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-6');
INSERT INTO dist_track (track_id, platform, url) VALUES (52, 'spotify', 'https://open.spotify.com/track/14bAmUNLjA4ihHlJOYON4H');
INSERT INTO dist_track (track_id, platform, url) VALUES (53, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-7');
INSERT INTO dist_track (track_id, platform, url) VALUES (53, 'spotify', 'https://open.spotify.com/track/4URjLXIQo1Ta7NMfPrPFbK');
INSERT INTO dist_track (track_id, platform, url) VALUES (54, 'bandcamp', 'https://spartalien.bandcamp.com/track/roadblock');
INSERT INTO dist_track (track_id, platform, url) VALUES (54, 'spotify', 'https://open.spotify.com/track/4ZBBu2MPQrIu7n8wojWJQ0');
INSERT INTO dist_track (track_id, platform, url) VALUES (55, 'bandcamp', 'https://spartalien.bandcamp.com/track/escape');
INSERT INTO dist_track (track_id, platform, url) VALUES (55, 'spotify', 'https://open.spotify.com/track/6xjdzkhkdNWc6nyoclqvpD');
INSERT INTO dist_track (track_id, platform, url) VALUES (56, 'bandcamp', 'https://spartalien.bandcamp.com/track/freedom');
INSERT INTO dist_track (track_id, platform, url) VALUES (56, 'spotify', 'https://open.spotify.com/track/3VlUqe89TX0TAtdU7v7bom');
INSERT INTO dist_track (track_id, platform, url) VALUES (57, 'bandcamp', 'https://spartalien.bandcamp.com/track/vigilant');
INSERT INTO dist_track (track_id, platform, url) VALUES (57, 'spotify', 'https://open.spotify.com/track/7LzkBQNlfQSab53sSYCF1Z');
INSERT INTO dist_track (track_id, platform, url) VALUES (58, 'bandcamp', 'https://spartalien.bandcamp.com/track/rainbows-unicorns');
INSERT INTO dist_track (track_id, platform, url) VALUES (58, 'spotify', 'https://open.spotify.com/track/3flUCe6A3SQWJ86hMP0xpU');
INSERT INTO dist_track (track_id, platform, url) VALUES (59, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-8');
INSERT INTO dist_track (track_id, platform, url) VALUES (59, 'spotify', 'https://open.spotify.com/track/2TwtGPgQrtmwcdr9TT23dI');
INSERT INTO dist_track (track_id, platform, url) VALUES (60, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (60, 'spotify', 'https://open.spotify.com/track/6ay8IxkPDwobHqZibilMsZ');
INSERT INTO dist_track (track_id, platform, url) VALUES (61, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-1-waveless-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (61, 'spotify', 'https://open.spotify.com/track/2Z7QRSClW2clm7p4zKY2H2');
INSERT INTO dist_track (track_id, platform, url) VALUES (62, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-9');
INSERT INTO dist_track (track_id, platform, url) VALUES (62, 'spotify', 'https://open.spotify.com/track/3qeZZXB3eqaR3V4RZrnxDl');
INSERT INTO dist_track (track_id, platform, url) VALUES (63, 'bandcamp', 'https://spartalien.bandcamp.com/track/unfamiliar-intro');
INSERT INTO dist_track (track_id, platform, url) VALUES (63, 'spotify', 'https://open.spotify.com/track/06NdC0dLnayARLh7N36w2d');
INSERT INTO dist_track (track_id, platform, url) VALUES (64, 'bandcamp', 'https://spartalien.bandcamp.com/track/nightlife');
INSERT INTO dist_track (track_id, platform, url) VALUES (64, 'spotify', 'https://open.spotify.com/track/2kgMrH28YQmhQZSpjItQ5W');
INSERT INTO dist_track (track_id, platform, url) VALUES (65, 'bandcamp', 'https://spartalien.bandcamp.com/track/together');
INSERT INTO dist_track (track_id, platform, url) VALUES (65, 'spotify', 'https://open.spotify.com/track/2C1WkGqkxlLJPDzWkRYNug');
INSERT INTO dist_track (track_id, platform, url) VALUES (66, 'bandcamp', 'https://spartalien.bandcamp.com/track/transitting-wormhole-s9a5-1-interlude-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (66, 'spotify', 'https://open.spotify.com/track/0RfqnG7iQhUwpRCAPAI1ON');
INSERT INTO dist_track (track_id, platform, url) VALUES (67, 'bandcamp', 'https://spartalien.bandcamp.com/track/ghosts');
INSERT INTO dist_track (track_id, platform, url) VALUES (67, 'spotify', 'https://open.spotify.com/track/0QTJUDIID4fsVRrpdLf8yE');
INSERT INTO dist_track (track_id, platform, url) VALUES (68, 'bandcamp', 'https://spartalien.bandcamp.com/track/help');
INSERT INTO dist_track (track_id, platform, url) VALUES (68, 'spotify', 'https://open.spotify.com/track/6S2F1sRVauzlRRcLEhmcPC');
INSERT INTO dist_track (track_id, platform, url) VALUES (69, 'bandcamp', 'https://spartalien.bandcamp.com/track/transitting-wormhole-s9a5-2-interlude-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (69, 'spotify', 'https://open.spotify.com/track/0h7Tb3oJOKZJUX4x0VFmx2');
INSERT INTO dist_track (track_id, platform, url) VALUES (70, 'bandcamp', 'https://spartalien.bandcamp.com/track/utopia');
INSERT INTO dist_track (track_id, platform, url) VALUES (70, 'spotify', 'https://open.spotify.com/track/2jWFJJOh3D3qZZaMoEvExR');
INSERT INTO dist_track (track_id, platform, url) VALUES (71, 'bandcamp', 'https://spartalien.bandcamp.com/track/crossroads');
INSERT INTO dist_track (track_id, platform, url) VALUES (71, 'spotify', 'https://open.spotify.com/track/5DslAltl6KENxMz8gvOP8p');
INSERT INTO dist_track (track_id, platform, url) VALUES (72, 'bandcamp', 'https://spartalien.bandcamp.com/track/transitting-wormhole-s9a5-3-interlude-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (72, 'spotify', 'https://open.spotify.com/track/7nEa9d41U0LxpULdrDfQ9T');
INSERT INTO dist_track (track_id, platform, url) VALUES (73, 'bandcamp', 'https://spartalien.bandcamp.com/track/ragazzi');
INSERT INTO dist_track (track_id, platform, url) VALUES (73, 'spotify', 'https://open.spotify.com/track/11imSz1EM6mvzIP13aO9el');
INSERT INTO dist_track (track_id, platform, url) VALUES (74, 'bandcamp', 'https://spartalien.bandcamp.com/track/realm');
INSERT INTO dist_track (track_id, platform, url) VALUES (74, 'spotify', 'https://open.spotify.com/track/1E8If3NDEpNR896z31FYCT');
INSERT INTO dist_track (track_id, platform, url) VALUES (75, 'bandcamp', 'https://spartalien.bandcamp.com/track/singularity-outro');
INSERT INTO dist_track (track_id, platform, url) VALUES (75, 'spotify', 'https://open.spotify.com/track/3b0KxM2B3yK3JI7sTl8t5k');
INSERT INTO dist_track (track_id, platform, url) VALUES (76, 'bandcamp', 'https://spartalien.bandcamp.com/track/brain-i-o-10');
INSERT INTO dist_track (track_id, platform, url) VALUES (76, 'spotify', 'https://open.spotify.com/track/5WNdr0xgKuF5LAA5WZwGNY');
INSERT INTO dist_track (track_id, platform, url) VALUES (77, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (77, 'spotify', 'https://open.spotify.com/track/4BSvFRMbcmlZFg26mND7cc');
INSERT INTO dist_track (track_id, platform, url) VALUES (78, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-2-binaural-headphone-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (78, 'spotify', 'https://open.spotify.com/track/5UEiOT5JwbKSA2UIzXHTQc');
INSERT INTO dist_track (track_id, platform, url) VALUES (79, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-2-weatherless-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (79, 'spotify', 'https://open.spotify.com/track/25CSmsKHfHbxwwNvtEC8vy');
INSERT INTO dist_track (track_id, platform, url) VALUES (80, 'bandcamp', 'https://spartalien.bandcamp.com/track/let-it-all-go-volume-2-weatherless-droneless-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (80, 'spotify', 'https://open.spotify.com/track/7g08H1n0EWxmtB43h0bjdu');
INSERT INTO dist_track (track_id, platform, url) VALUES (81, 'bandcamp', 'https://spartalien.bandcamp.com/track/wooden-bench');
INSERT INTO dist_track (track_id, platform, url) VALUES (81, 'spotify', 'https://open.spotify.com/track/6DhvXSEHtkFzaLaaPSO3Oa');
INSERT INTO dist_track (track_id, platform, url) VALUES (82, 'bandcamp', 'https://spartalien.bandcamp.com/track/reconquer');
INSERT INTO dist_track (track_id, platform, url) VALUES (82, 'spotify', 'https://open.spotify.com/track/13L80sdXImnLjNTIzuwQtx');
INSERT INTO dist_track (track_id, platform, url) VALUES (83, 'bandcamp', 'https://spartalien.bandcamp.com/track/answering-machine');
INSERT INTO dist_track (track_id, platform, url) VALUES (83, 'spotify', 'https://open.spotify.com/track/7IThxfB81NKWFYi3LDfGjg');
INSERT INTO dist_track (track_id, platform, url) VALUES (84, 'bandcamp', 'https://spartalien.bandcamp.com/track/sandy-ice-cream');
INSERT INTO dist_track (track_id, platform, url) VALUES (84, 'spotify', 'https://open.spotify.com/track/5KoRzFBozMzmNZlMTEZYqb');
INSERT INTO dist_track (track_id, platform, url) VALUES (85, 'bandcamp', 'https://spartalien.bandcamp.com/track/detuned-present');
INSERT INTO dist_track (track_id, platform, url) VALUES (85, 'spotify', 'https://open.spotify.com/track/687eT7aPAp61rAbRAh0U8z');
INSERT INTO dist_track (track_id, platform, url) VALUES (86, 'bandcamp', 'https://spartalien.bandcamp.com/track/after-all');
INSERT INTO dist_track (track_id, platform, url) VALUES (86, 'spotify', 'https://open.spotify.com/track/7sn46QinnWB7YOD2DKbSfn');
INSERT INTO dist_track (track_id, platform, url) VALUES (87, 'bandcamp', 'https://spartalien.bandcamp.com/track/push');
INSERT INTO dist_track (track_id, platform, url) VALUES (87, 'spotify', 'https://open.spotify.com/track/21Ko68BYn2s21GxVtiNKrF');
INSERT INTO dist_track (track_id, platform, url) VALUES (88, 'bandcamp', 'https://spartalien.bandcamp.com/track/rusty-playground');
INSERT INTO dist_track (track_id, platform, url) VALUES (88, 'spotify', 'https://open.spotify.com/track/0ftEwQnHTdNwCz2muSMQMb');
INSERT INTO dist_track (track_id, platform, url) VALUES (89, 'bandcamp', 'https://spartalien.bandcamp.com/track/pull');
INSERT INTO dist_track (track_id, platform, url) VALUES (89, 'spotify', 'https://open.spotify.com/track/0DGO8z59f3hKa4ajszpfdg');
INSERT INTO dist_track (track_id, platform, url) VALUES (90, 'bandcamp', 'https://spartalien.bandcamp.com/track/you-are-not-them');
INSERT INTO dist_track (track_id, platform, url) VALUES (90, 'spotify', 'https://open.spotify.com/track/5OhmXlLolp4wTUy7H4ZFxF');
INSERT INTO dist_track (track_id, platform, url) VALUES (91, 'bandcamp', 'https://spartalien.bandcamp.com/track/a-night-with-my-imaginary-friend');
INSERT INTO dist_track (track_id, platform, url) VALUES (92, 'bandcamp', 'https://spartalien.bandcamp.com/track/uncertain');
INSERT INTO dist_track (track_id, platform, url) VALUES (92, 'spotify', 'https://open.spotify.com/track/4A9uz51yEBcHImxUXnhABw');
INSERT INTO dist_track (track_id, platform, url) VALUES (93, 'bandcamp', 'https://spartalien.bandcamp.com/track/anomaly');
INSERT INTO dist_track (track_id, platform, url) VALUES (93, 'spotify', 'https://open.spotify.com/track/01W2H0tACbOKrTbB5ryfvO');
INSERT INTO dist_track (track_id, platform, url) VALUES (94, 'bandcamp', 'https://spartalien.bandcamp.com/track/secret');
INSERT INTO dist_track (track_id, platform, url) VALUES (94, 'spotify', 'https://open.spotify.com/track/6tGh0r6YeWdCZIjOI7ZmDI');
INSERT INTO dist_track (track_id, platform, url) VALUES (95, 'bandcamp', 'https://spartalien.bandcamp.com/track/polychrome');
INSERT INTO dist_track (track_id, platform, url) VALUES (95, 'spotify', 'https://open.spotify.com/track/7zc6wLW9FW3gM3LZ9g53Dw');
INSERT INTO dist_track (track_id, platform, url) VALUES (96, 'bandcamp', 'https://spartalien.bandcamp.com/track/irresistible');
INSERT INTO dist_track (track_id, platform, url) VALUES (96, 'spotify', 'https://open.spotify.com/track/4NHBowOzv6rqDgtzsOPpsf');
INSERT INTO dist_track (track_id, platform, url) VALUES (97, 'bandcamp', 'https://spartalien.bandcamp.com/track/flux-feat-stevie-lee-price');
INSERT INTO dist_track (track_id, platform, url) VALUES (97, 'spotify', 'https://open.spotify.com/track/4ODKqMpXVASOtIxZNDGVfR');
INSERT INTO dist_track (track_id, platform, url) VALUES (98, 'bandcamp', 'https://spartalien.bandcamp.com/track/flux-instrumental-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (98, 'spotify', 'https://open.spotify.com/track/2mMUm5AJo5DBCJgDKjRfhe');
INSERT INTO dist_track (track_id, platform, url) VALUES (99, 'bandcamp', 'https://spartalien.bandcamp.com/track/flux-ambient-mix');
INSERT INTO dist_track (track_id, platform, url) VALUES (99, 'spotify', 'https://open.spotify.com/track/17xUr5skLolIMBKsY0HUPe');
INSERT INTO dist_track (track_id, platform, url) VALUES (100, 'bandcamp', 'https://spartalien.bandcamp.com/track/haphe-spartaliens-wicca-remix');
INSERT INTO dist_track (track_id, platform, url) VALUES (101, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-once');
INSERT INTO dist_track (track_id, platform, url) VALUES (101, 'spotify', 'https://open.spotify.com/track/0AIWe5VI1jRW9689HIUiFw');
INSERT INTO dist_track (track_id, platform, url) VALUES (102, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-maybe');
INSERT INTO dist_track (track_id, platform, url) VALUES (102, 'spotify', 'https://open.spotify.com/track/1l4ixFxHyH28iqHiHhc7Hh');
INSERT INTO dist_track (track_id, platform, url) VALUES (103, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-mountain');
INSERT INTO dist_track (track_id, platform, url) VALUES (103, 'spotify', 'https://open.spotify.com/track/6IdfaVVlpsudR6Um2wsuYx');
INSERT INTO dist_track (track_id, platform, url) VALUES (104, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-ice');
INSERT INTO dist_track (track_id, platform, url) VALUES (104, 'spotify', 'https://open.spotify.com/track/2SURwFUAdWln1HDEFDtOdW');
INSERT INTO dist_track (track_id, platform, url) VALUES (105, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-why');
INSERT INTO dist_track (track_id, platform, url) VALUES (105, 'spotify', 'https://open.spotify.com/track/5oUwPxVIPwKQ1RbkEtiOGG');
INSERT INTO dist_track (track_id, platform, url) VALUES (106, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-real');
INSERT INTO dist_track (track_id, platform, url) VALUES (106, 'spotify', 'https://open.spotify.com/track/3o5zo6IZFCqG7mPGQazNQW');
INSERT INTO dist_track (track_id, platform, url) VALUES (107, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-same');
INSERT INTO dist_track (track_id, platform, url) VALUES (107, 'spotify', 'https://open.spotify.com/track/5Gp2vhoG89FXf2epYt9US2');
INSERT INTO dist_track (track_id, platform, url) VALUES (108, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-tower');
INSERT INTO dist_track (track_id, platform, url) VALUES (108, 'spotify', 'https://open.spotify.com/track/4odjnZN1hRgmzCeHzmbtoz');
INSERT INTO dist_track (track_id, platform, url) VALUES (109, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-not');
INSERT INTO dist_track (track_id, platform, url) VALUES (109, 'spotify', 'https://open.spotify.com/track/7JiUn9S4eZFavW8SADuLmm');
INSERT INTO dist_track (track_id, platform, url) VALUES (110, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-if');
INSERT INTO dist_track (track_id, platform, url) VALUES (110, 'spotify', 'https://open.spotify.com/track/2qvQHB4HXj1QPlO07DhI25');
INSERT INTO dist_track (track_id, platform, url) VALUES (111, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-tales');
INSERT INTO dist_track (track_id, platform, url) VALUES (111, 'spotify', 'https://open.spotify.com/track/1tH6Gx59JCmwr4hlS9JSdT');
INSERT INTO dist_track (track_id, platform, url) VALUES (112, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-unconditional');
INSERT INTO dist_track (track_id, platform, url) VALUES (112, 'spotify', 'https://open.spotify.com/track/1ATIlA1xcTU1GHzLknOZxX');
INSERT INTO dist_track (track_id, platform, url) VALUES (113, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-arrival');
INSERT INTO dist_track (track_id, platform, url) VALUES (113, 'spotify', 'https://open.spotify.com/track/5j9ba2nHiqXuny74KBsdpu');
INSERT INTO dist_track (track_id, platform, url) VALUES (114, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-with');
INSERT INTO dist_track (track_id, platform, url) VALUES (114, 'spotify', 'https://open.spotify.com/track/0QruXMi58YT7uXtmGPD6tE');
INSERT INTO dist_track (track_id, platform, url) VALUES (115, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-stumble');
INSERT INTO dist_track (track_id, platform, url) VALUES (115, 'spotify', 'https://open.spotify.com/track/0pMxR3Pa977QcUvoT3cRHy');
INSERT INTO dist_track (track_id, platform, url) VALUES (116, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-torpedo');
INSERT INTO dist_track (track_id, platform, url) VALUES (116, 'spotify', 'https://open.spotify.com/track/3HIaJ4YpLHALYklCc7lBgk');
INSERT INTO dist_track (track_id, platform, url) VALUES (117, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-sometime');
INSERT INTO dist_track (track_id, platform, url) VALUES (117, 'spotify', 'https://open.spotify.com/track/3FN1Fx2SWXADTBTmp4Gd2I');
INSERT INTO dist_track (track_id, platform, url) VALUES (118, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-1-castle');
INSERT INTO dist_track (track_id, platform, url) VALUES (118, 'spotify', 'https://open.spotify.com/track/5fwxA270bKqWYNyPUo2MHs');
INSERT INTO dist_track (track_id, platform, url) VALUES (119, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-prayer');
INSERT INTO dist_track (track_id, platform, url) VALUES (119, 'spotify', 'https://open.spotify.com/track/3xSSgSqbuoFpTO7mY4YAWC');
INSERT INTO dist_track (track_id, platform, url) VALUES (120, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-wait');
INSERT INTO dist_track (track_id, platform, url) VALUES (120, 'spotify', 'https://open.spotify.com/track/0meu38RtpPP9HJaYBuVRkI');
INSERT INTO dist_track (track_id, platform, url) VALUES (121, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-cargo');
INSERT INTO dist_track (track_id, platform, url) VALUES (121, 'spotify', 'https://open.spotify.com/track/7AHrW4EPnFBCfdW9RZfXJL');
INSERT INTO dist_track (track_id, platform, url) VALUES (122, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-volcano');
INSERT INTO dist_track (track_id, platform, url) VALUES (122, 'spotify', 'https://open.spotify.com/track/2eCJnLwAkTDEDQ5PZsnnm9');
INSERT INTO dist_track (track_id, platform, url) VALUES (123, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-cave');
INSERT INTO dist_track (track_id, platform, url) VALUES (123, 'spotify', 'https://open.spotify.com/track/3hzQJiyubKn2v9WJUeNKbO');
INSERT INTO dist_track (track_id, platform, url) VALUES (124, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-resolution');
INSERT INTO dist_track (track_id, platform, url) VALUES (124, 'spotify', 'https://open.spotify.com/track/0Zt5BQrs4WDtZEtbCuh0vE');
INSERT INTO dist_track (track_id, platform, url) VALUES (125, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-reunion');
INSERT INTO dist_track (track_id, platform, url) VALUES (125, 'spotify', 'https://open.spotify.com/track/3y9fDvhSvvDY3ASJKlciEz');
INSERT INTO dist_track (track_id, platform, url) VALUES (126, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-decay');
INSERT INTO dist_track (track_id, platform, url) VALUES (126, 'spotify', 'https://open.spotify.com/track/2f6iyOCn6LVPGrAuowbb4k');
INSERT INTO dist_track (track_id, platform, url) VALUES (127, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-breach');
INSERT INTO dist_track (track_id, platform, url) VALUES (127, 'spotify', 'https://open.spotify.com/track/1aHpal4HkhgwOwvZP9UQTT');
INSERT INTO dist_track (track_id, platform, url) VALUES (128, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-unlocked');
INSERT INTO dist_track (track_id, platform, url) VALUES (128, 'spotify', 'https://open.spotify.com/track/5Xe7LCAqPt10e6w2DJvUpi');
INSERT INTO dist_track (track_id, platform, url) VALUES (129, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-2-thrive');
INSERT INTO dist_track (track_id, platform, url) VALUES (129, 'spotify', 'https://open.spotify.com/track/4uqnJNdUKWOTZQ3bRstAcg');
INSERT INTO dist_track (track_id, platform, url) VALUES (130, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-three');
INSERT INTO dist_track (track_id, platform, url) VALUES (130, 'spotify', 'https://open.spotify.com/track/1BtMtpGXcdbmdWEyVIkZit');
INSERT INTO dist_track (track_id, platform, url) VALUES (131, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-valley');
INSERT INTO dist_track (track_id, platform, url) VALUES (131, 'spotify', 'https://open.spotify.com/track/64aXTILxznqvVjZK4PRgZp');
INSERT INTO dist_track (track_id, platform, url) VALUES (132, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-rope');
INSERT INTO dist_track (track_id, platform, url) VALUES (132, 'spotify', 'https://open.spotify.com/track/6qPKwVMqpFGCCYg1FKT8iX');
INSERT INTO dist_track (track_id, platform, url) VALUES (133, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-carusel');
INSERT INTO dist_track (track_id, platform, url) VALUES (133, 'spotify', 'https://open.spotify.com/track/6ovkYgTM6pFMyQcpuLCTc5');
INSERT INTO dist_track (track_id, platform, url) VALUES (134, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-angel');
INSERT INTO dist_track (track_id, platform, url) VALUES (134, 'spotify', 'https://open.spotify.com/track/5NfxwhIgYBrea7TH88KCfK');
INSERT INTO dist_track (track_id, platform, url) VALUES (135, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-miss');
INSERT INTO dist_track (track_id, platform, url) VALUES (135, 'spotify', 'https://open.spotify.com/track/5WweS23l0bftflz3lMnJiD');
INSERT INTO dist_track (track_id, platform, url) VALUES (136, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-here');
INSERT INTO dist_track (track_id, platform, url) VALUES (136, 'spotify', 'https://open.spotify.com/track/7ovO4gYw0o0JNStyCCWX79');
INSERT INTO dist_track (track_id, platform, url) VALUES (137, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-envelope');
INSERT INTO dist_track (track_id, platform, url) VALUES (137, 'spotify', 'https://open.spotify.com/track/5qJ6WjHqE3nDLGS3WoD3B4');
INSERT INTO dist_track (track_id, platform, url) VALUES (138, 'bandcamp', 'https://spartalien.bandcamp.com/track/chapter-3-alps');
INSERT INTO dist_track (track_id, platform, url) VALUES (138, 'spotify', 'https://open.spotify.com/track/4pUqWuZbo608l3SWk4y22g');
INSERT INTO dist_track (track_id, platform, url) VALUES (139, 'bandcamp', 'https://spartalien.bandcamp.com/track/doomers-delight-chapter-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (139, 'spotify', 'https://open.spotify.com/track/3UVuargrscLQKAv7QCETnW');
INSERT INTO dist_track (track_id, platform, url) VALUES (140, 'bandcamp', 'https://spartalien.bandcamp.com/track/doomers-delight-chapter-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (140, 'spotify', 'https://open.spotify.com/track/7reeFcYzOTzxSE8ruZ7KMS');
INSERT INTO dist_track (track_id, platform, url) VALUES (141, 'bandcamp', 'https://spartalien.bandcamp.com/track/doomers-delight-chapter-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (141, 'spotify', 'https://open.spotify.com/track/1JktcLRqQL5kWDHG39Cxfa');
INSERT INTO dist_track (track_id, platform, url) VALUES (142, 'bandcamp', 'https://spartalien.bandcamp.com/track/four-four-three');
INSERT INTO dist_track (track_id, platform, url) VALUES (142, 'spotify', 'https://open.spotify.com/track/39qiokZA1gAUKfAs41UpWd');
INSERT INTO dist_track (track_id, platform, url) VALUES (143, 'bandcamp', 'https://spartalien.bandcamp.com/track/city-lights');
INSERT INTO dist_track (track_id, platform, url) VALUES (143, 'spotify', 'https://open.spotify.com/track/21ibSwxJvgc59ZTc4nPITu');
INSERT INTO dist_track (track_id, platform, url) VALUES (144, 'bandcamp', 'https://spartalien.bandcamp.com/track/final-adventure');
INSERT INTO dist_track (track_id, platform, url) VALUES (144, 'spotify', 'https://open.spotify.com/track/295ySgcaeRrUupsxC2ehdl');
INSERT INTO dist_track (track_id, platform, url) VALUES (145, 'bandcamp', 'https://spartalien.bandcamp.com/track/el-loco');
INSERT INTO dist_track (track_id, platform, url) VALUES (145, 'spotify', 'https://open.spotify.com/track/5FhPYqpIR4nvf6FB2uZMQG');
INSERT INTO dist_track (track_id, platform, url) VALUES (146, 'bandcamp', 'https://spartalien.bandcamp.com/track/tracked');
INSERT INTO dist_track (track_id, platform, url) VALUES (146, 'spotify', 'https://open.spotify.com/track/3LinfNouFExDPK4Y7IeBDt');
INSERT INTO dist_track (track_id, platform, url) VALUES (147, 'bandcamp', 'https://spartalien.bandcamp.com/track/smoking-sea');
INSERT INTO dist_track (track_id, platform, url) VALUES (147, 'spotify', 'https://open.spotify.com/track/0zUT4DnBAV7MvYe52Dtjzn');
INSERT INTO dist_track (track_id, platform, url) VALUES (148, 'bandcamp', 'https://spartalien.bandcamp.com/track/four-four-three-we-ded-version');
INSERT INTO dist_track (track_id, platform, url) VALUES (148, 'spotify', 'https://open.spotify.com/track/1kNC0ai1R7VUHSfq5lWK52');
INSERT INTO dist_track (track_id, platform, url) VALUES (149, 'bandcamp', 'https://spartalien.bandcamp.com/track/final-adventure-not-a-tale-version');
INSERT INTO dist_track (track_id, platform, url) VALUES (149, 'spotify', 'https://open.spotify.com/track/0M8W2PyMIQxHtqTaZ4hnvV');
INSERT INTO dist_track (track_id, platform, url) VALUES (150, 'bandcamp', 'https://spartalien.bandcamp.com/track/smoking-sea-feat-orochi-hanma');
INSERT INTO dist_track (track_id, platform, url) VALUES (150, 'spotify', 'https://open.spotify.com/track/1R8hHZc8kwnk2waV0k6WBm');
INSERT INTO dist_track (track_id, platform, url) VALUES (151, 'bandcamp', 'https://spartalien.bandcamp.com/track/compost-heap-triangle');
INSERT INTO dist_track (track_id, platform, url) VALUES (151, 'spotify', 'https://open.spotify.com/track/0eUAzePwWBTKNSGwzQqTGE');
INSERT INTO dist_track (track_id, platform, url) VALUES (152, 'bandcamp', 'https://spartalien.bandcamp.com/track/to-return-home');
INSERT INTO dist_track (track_id, platform, url) VALUES (152, 'spotify', 'https://open.spotify.com/track/1HnqNBKaXVs6qpdhAcOLoR');
INSERT INTO dist_track (track_id, platform, url) VALUES (153, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-memory');
INSERT INTO dist_track (track_id, platform, url) VALUES (153, 'spotify', 'https://open.spotify.com/track/0fDT8IfjyjlI3kHY5eE8gi');
INSERT INTO dist_track (track_id, platform, url) VALUES (154, 'bandcamp', 'https://spartalien.bandcamp.com/track/biting-wind');
INSERT INTO dist_track (track_id, platform, url) VALUES (154, 'spotify', 'https://open.spotify.com/track/5ooK6ib7W42Ren56P2v6lM');
INSERT INTO dist_track (track_id, platform, url) VALUES (155, 'bandcamp', 'https://spartalien.bandcamp.com/track/with-darkness-comes-clarity');
INSERT INTO dist_track (track_id, platform, url) VALUES (155, 'spotify', 'https://open.spotify.com/track/3vHGVj1Mr6K9GTlLdvGnhn');
INSERT INTO dist_track (track_id, platform, url) VALUES (156, 'bandcamp', 'https://spartalien.bandcamp.com/track/full-moon');
INSERT INTO dist_track (track_id, platform, url) VALUES (156, 'spotify', 'https://open.spotify.com/track/0nWNpXREKPhSj1ErOPPEKq');
INSERT INTO dist_track (track_id, platform, url) VALUES (157, 'bandcamp', 'https://spartalien.bandcamp.com/track/his-task');
INSERT INTO dist_track (track_id, platform, url) VALUES (157, 'spotify', 'https://open.spotify.com/track/14Ebgu4S2HVQQP29uSXbZh');
INSERT INTO dist_track (track_id, platform, url) VALUES (158, 'bandcamp', 'https://spartalien.bandcamp.com/track/knees-on-the-floor');
INSERT INTO dist_track (track_id, platform, url) VALUES (158, 'spotify', 'https://open.spotify.com/track/389xxnKRUBfhvp2fMZGLde');
INSERT INTO dist_track (track_id, platform, url) VALUES (159, 'bandcamp', 'https://spartalien.bandcamp.com/track/never-arriving');
INSERT INTO dist_track (track_id, platform, url) VALUES (159, 'spotify', 'https://open.spotify.com/track/689FWlODwQKh0doecR8vu8');
INSERT INTO dist_track (track_id, platform, url) VALUES (160, 'bandcamp', 'https://spartalien.bandcamp.com/track/collective-departure');
INSERT INTO dist_track (track_id, platform, url) VALUES (160, 'spotify', 'https://open.spotify.com/track/13rYRXh4G96DkkNgPxwaIl');
INSERT INTO dist_track (track_id, platform, url) VALUES (161, 'bandcamp', 'https://spartalien.bandcamp.com/track/i-have-seen-the-shadow-again');
INSERT INTO dist_track (track_id, platform, url) VALUES (162, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-1');
INSERT INTO dist_track (track_id, platform, url) VALUES (163, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-2');
INSERT INTO dist_track (track_id, platform, url) VALUES (164, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-3');
INSERT INTO dist_track (track_id, platform, url) VALUES (165, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-4');
INSERT INTO dist_track (track_id, platform, url) VALUES (166, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-5');
INSERT INTO dist_track (track_id, platform, url) VALUES (167, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-6');
INSERT INTO dist_track (track_id, platform, url) VALUES (168, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-7');
INSERT INTO dist_track (track_id, platform, url) VALUES (169, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-8');
INSERT INTO dist_track (track_id, platform, url) VALUES (170, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-9');
INSERT INTO dist_track (track_id, platform, url) VALUES (171, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-dying-spaceship-symphony-part-10');
INSERT INTO dist_track (track_id, platform, url) VALUES (172, 'bandcamp', 'https://spartalien.bandcamp.com/track/yellow-soul-grinder');
INSERT INTO dist_track (track_id, platform, url) VALUES (172, 'spotify', 'https://open.spotify.com/track/2n76dGZUojcVJ1nsN72Mro');


INSERT INTO dist_rls (rls_id, platform, url) VALUES (1, 'bandcamp', 'https://spartalien.bandcamp.com/track/continuoduction');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (1, 'spotify', 'https://open.spotify.com/track/2Clx7jPmYSA21DbB0FKxUR');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (2, 'bandcamp', 'https://spartalien.bandcamp.com/track/ill-embrace-you-again-in-space');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (2, 'spotify', 'https://open.spotify.com/track/3QmCKvjLtKXS4vQD6822rf');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (3, 'bandcamp', 'https://spartalien.bandcamp.com/track/realize-its-just-a-ride');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (3, 'spotify', 'https://open.spotify.com/track/6R28LmtWTwaggp496VUZKN');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (4, 'bandcamp', 'https://spartalien.bandcamp.com/track/natures-song');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (4, 'spotify', 'https://open.spotify.com/track/0Fnu4vn6XsiUpI2ECJyr5K');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (5, 'bandcamp', 'https://spartalien.bandcamp.com/track/following-the-calling');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (5, 'spotify', 'https://open.spotify.com/track/5DlhcOQXlUESTOhNWL4wQ5');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (6, 'bandcamp', 'https://spartalien.bandcamp.com/track/digging-in-memories');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (6, 'spotify', 'https://open.spotify.com/track/5JmknWTUqtJZ2Qhb3MMoCo');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (7, 'bandcamp', 'https://spartalien.bandcamp.com/track/heat-resistant');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (7, 'spotify', 'https://open.spotify.com/track/3VikP8t1yyx98cPKTinZDO');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (8, 'bandcamp', 'https://spartalien.bandcamp.com/track/song-for-wind');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (8, 'spotify', 'https://open.spotify.com/track/6Y5r9u7mHDudhTx90XTEF3');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (9, 'bandcamp', 'https://spartalien.bandcamp.com/track/messaggio-per-naelog');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (9, 'spotify', 'https://open.spotify.com/track/2bwflOuvNhQgtaCA4zI40e');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (10, 'bandcamp', 'https://spartalien.bandcamp.com/track/martina');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (10, 'spotify', 'https://open.spotify.com/track/6FSbzkJMMxfi9o2QopDW2W');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (11, 'bandcamp', 'https://spartalien.bandcamp.com/track/time');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (11, 'spotify', 'https://open.spotify.com/track/3AGRNrD23jzBOThTUGvygn');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (12, 'bandcamp', 'https://spartalien.bandcamp.com/track/every-day');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (12, 'spotify', 'https://open.spotify.com/track/3XStzziKE8h0Hzw6cT5OAd');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (13, 'bandcamp', 'https://spartalien.bandcamp.com/album/monolog');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (13, 'spotify', 'https://open.spotify.com/album/2KnU3c5IXpYtHsdJLYS47D');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (14, 'bandcamp', 'https://spartalien.bandcamp.com/track/searching');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (14, 'spotify', 'https://open.spotify.com/track/0zFZIbuKaLJ0bm9MecHfk0');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (15, 'bandcamp', 'https://spartalien.bandcamp.com/album/the-great-filter');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (15, 'spotify', 'https://open.spotify.com/album/052gFoANpMCUET2C21MUqh');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (16, 'bandcamp', 'https://spartalien.bandcamp.com/album/2358');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (16, 'spotify', 'https://open.spotify.com/album/74TE0Q53NLubkkZyHm8bNJ');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (17, 'bandcamp', 'https://spartalien.bandcamp.com/track/frozen-memories');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (17, 'spotify', 'https://open.spotify.com/track/6rSSRx7JdtdWdbNn7gS5Pl');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (18, 'bandcamp', 'https://spartalien.bandcamp.com/album/brain-i-o');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (18, 'spotify', 'https://open.spotify.com/playlist/2LF6a2ASNVlKiutk1tADG9');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (19, 'bandcamp', 'https://spartalien.bandcamp.com/track/they-shot-my-friend');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (19, 'spotify', 'https://open.spotify.com/track/6gcULl01jPOsWwn2EwVWHM');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (20, 'bandcamp', 'https://spartalien.bandcamp.com/track/the-sad-lightness-of-being');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (20, 'spotify', 'https://open.spotify.com/track/2onyU5yxSx9FhxtBgGoykG');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (21, 'bandcamp', 'https://spartalien.bandcamp.com/album/keen');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (21, 'spotify', 'https://open.spotify.com/album/7iQax3iHA9OilsTq9dM2nl');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (22, 'bandcamp', 'https://spartalien.bandcamp.com/track/rainbows-unicorns');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (22, 'spotify', 'https://open.spotify.com/track/3flUCe6A3SQWJ86hMP0xpU');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (23, 'bandcamp', 'https://spartalien.bandcamp.com/album/let-it-all-go-volume-1');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (23, 'spotify', 'https://open.spotify.com/album/5tQQhtJuFAa1IjOnBNLLzX');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (24, 'bandcamp', 'https://spartalien.bandcamp.com/album/1996');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (24, 'spotify', 'https://open.spotify.com/album/2ASJu0rQC3x7WiCwBN0VuL');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (25, 'bandcamp', 'https://spartalien.bandcamp.com/album/let-it-all-go-volume-2');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (25, 'spotify', 'https://open.spotify.com/album/0HPDjHHVdD4Es2gSckjK3r');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (26, 'bandcamp', 'https://spartalien.bandcamp.com/album/chill-tracks-2016-2020');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (26, 'spotify', 'https://open.spotify.com/album/1Ak6UIUqcEN9xtzoB4r3ya');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (27, 'bandcamp', 'https://spartalien.bandcamp.com/album/floating-high');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (27, 'spotify', 'https://open.spotify.com/album/7rpbLuknkFeNBOscxZ5djs');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (28, 'bandcamp', 'https://spartalien.bandcamp.com/track/uncertain');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (28, 'spotify', 'https://open.spotify.com/track/4A9uz51yEBcHImxUXnhABw');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (29, 'bandcamp', 'https://spartalien.bandcamp.com/album/the-band-with-the-drummer-who-knew-only-one-rhythm');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (29, 'spotify', 'https://open.spotify.com/album/5GO8DT7O6oqhAz4Mwblslp');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (30, 'bandcamp', 'https://spartalien.bandcamp.com/album/flux');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (30, 'spotify', 'https://open.spotify.com/album/7nngUQbyI6LtVUA1JEJmiL');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (31, 'bandcamp', 'https://spartalien.bandcamp.com/track/haphe-spartaliens-wicca-remix');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (32, 'bandcamp', 'https://spartalien.bandcamp.com/album/untold-stories');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (32, 'spotify', 'https://open.spotify.com/album/5Z09PSUcbZioMV7UvRv7yw');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (33, 'bandcamp', 'https://spartalien.bandcamp.com/album/untold-stories-doomers-delight');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (33, 'spotify', 'https://open.spotify.com/album/3MBt8QE1l8kCWBW6QaM71e');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (34, 'bandcamp', 'https://spartalien.bandcamp.com/album/okay-but-can-you-rap-to-this');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (34, 'spotify', 'https://open.spotify.com/album/4CXDCmlFrKxbmQjkEINHQa');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (35, 'bandcamp', 'https://spartalien.bandcamp.com/album/warm-summer-evening');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (35, 'spotify', 'https://open.spotify.com/album/3faemmsL9qLqKsCz1Oa2lv');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (36, 'bandcamp', 'https://spartalien.bandcamp.com/album/the-dying-spaceship-symphony');
INSERT INTO dist_rls (rls_id, platform, url) VALUES (37, 'spotify', 'https://open.spotify.com/track/2n76dGZUojcVJ1nsN72Mro');


COMMIT;
