export const randomQuotes: randomQuotesType = [
    { author: `Anne Sexton`, quote: `As it has been said: Love and a cough, cannot be concealed. Even a small cough. Even a small love.` },
    { author: `Aristotle`, quote: `The aim of art is to represent not the outward appearance of things, but their inward significance.` },
    { author: `Banksy`, quote: `Art should comfort the disturbed and disturb the comfortable.` },
    { author: `Bill Hicks`, quote: `Life is only a dream and we are the imagination of ourselves.` },
    { author: `Charles Bukowski`, quote: `Poetry is what happens when nothing else can.` },
    { author: `Clive Barker`, quote: `Any fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.` },
    { author: `Dmitri Shostakovich`, quote: `When a man is in despair, it means that he still believes in something.` },
    { author: `E. E. Cummings`, quote: `To be nobody but yourself in a world which is doing its best day and night to make you like everybody else means to fight the hardest battle which any human being can fight and never stop fighting.` },
    { author: `Friedrich Nietzsche`, quote: `And those who were seen dancing were thought to be insane by those who could not hear the music.` },
    { author: `Friedrich Nietzsche`, quote: `You must have chaos within you to give birth to a dancing star.` },
    { author: `Gerard Way`, quote: `Would you destroy something perfect in order to make it beautiful?` },
    { author: `Joss Whedon`, quote: `All worthy work is open to interpretations the author did not intend. Art isn't your pet -- it's your kid. It grows up and talks back to you.` },
    { author: `Maria von Trapp`, quote: `Music acts like a magic key, to which the most tightly closed heart opens.` },
    { author: `Oscar Wilde`, quote: `Be yourself; everyone else is already taken.` },
    { author: `Pablo Picasso`, quote: `Art washes away from the soul the dust of everyday life.` },
    { author: `Pablo Picasso`, quote: `Every child is an artist. The problem is how to remain an artist once he grows up.` },
    { author: `Pablo Picasso`, quote: `Everything you can imagine is real.` },
    { author: `Prince`, quote: `Hard to say what's right when all I wanna do is wrong.` },
    { author: `Robert Frost`, quote: `Forgive, O Lord, my little jokes on Thee. And I'll forgive Thy great big one on me.` },
    { author: `Timothy Leary`, quote: `...as a guide and protection. Trust your divinity, trust your brain.` },
    { author: `Timothy Leary`, quote: `Think for yourself. Question authority.` },
    { author: `Tupac Shakur`, quote: `Death is not the greatest loss in life. The greatest loss is what dies inside while still alive. Never surrender.` },
    { author: `Tupac Shakur`, quote: `People tend to choke that which they do not understand.` },
    { author: `Tupac Shakur`, quote: `They got money for wars, but can't feed the poor.`},
    { author: `Victor Hugo`, quote: `Music expresses that which cannot be put into words and that which cannot remain silent.` },
    { author: `Vladimir Nabokov`, quote: `A writer should have the precision of a poet and the imagination of a scientist.` },
]
